#!/bin/bash

rm -rf .Rhistory \
       man \
       NAMESPACE \
       R/RcppExports.R \
       src/*o \
       src/RcppExports*

cat >NAMESPACE <<EOL
# Generated by roxygen2: do not edit by hand
EOL
