// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// voronoi
Rcpp::StringVector voronoi(Rcpp::NumericVector x, Rcpp::NumericVector y, Rcpp::NumericVector z, double containerRatio);
RcppExport SEXP _voro3d_voronoi(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP containerRatioSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type containerRatio(containerRatioSEXP);
    rcpp_result_gen = Rcpp::wrap(voronoi(x, y, z, containerRatio));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_voro3d_voronoi", (DL_FUNC) &_voro3d_voronoi, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_voro3d(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
