# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create Voronoi Diagram
#'
#' Create cell-based voronoi diagram using three-dimensional points. The
#'   polyhedral surface of each cell is defined in well-known text format.
#'
#' @param x numeric vector of the x-coordinates of the points
#' @param y numeric vector of the y-coordinates of the points
#' @param z numeric vector of the z-coordinates of the points
#' @param containerRatio numeric ratio between the length of the container to
#'   be created and the length of the bounding box of the points
#' @return character vector defining the voronoi cells (polyhedral surface)
#'   in well-known text
#' @export
voronoi <- function(x, y, z, containerRatio) {
    .Call('_voro3d_voronoi', PACKAGE = 'voro3d', x, y, z, containerRatio)
}

